spring:
  application:
    name: spring-ai-functions

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
aifunc:
  aiapp:
    ninjasApiKey: ${NINJAS_API_KEY}